### ISSUE TITLE
Werid error

### ISSUE THREAD

**Issue by PaladinFallen** [JEFF-Media-GbR/BetterTridents#5]
[16:21:29] [Server thread/ERROR]: [BetterTridents] [Configuration] An error occured while loading plugin.yml resource for plugin BetterTridents:
org.yaml.snakeyaml.constructor.ConstructorException: could not determine a constructor for the tag !@UTF8
 in 'reader', line 11, column 5:
      - !@UTF8
        ^

	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined.construct(SafeConstructor.java:620) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:469) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:435) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct(SafeConstructor.java:577) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270) ~[snakeyaml-1.33.jar:?]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253) ~[snakeyaml-1.33.jar:?]
	at org.bukkit.configuration.file.YamlConstructor.construct(YamlConstructor.java:27) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.fromNodeTree(YamlConfiguration.java:160) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:117) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at com.bergerkiller.bukkit.common.internal.logic.PluginLoaderHandler.<init>(PluginLoaderHandler.java:24) ~[BKCommonLib-1.19.3-v2-1501.jar:?]
	at com.bergerkiller.bukkit.common.internal.logic.PluginLoaderHandlerPaperFallback.<init>(PluginLoaderHandlerPaperFallback.java:19) ~[BKCommonLib-1.19.3-v2-1501.jar:?]
	at com.bergerkiller.bukkit.common.internal.logic.PluginLoaderHandler.createFor(PluginLoaderHandler.java:151) ~[BKCommonLib-1.19.3-v2-1501.jar:?]
	at com.bergerkiller.bukkit.common.internal.logic.PluginLoaderHandler.isPluginFullyEnabled(PluginLoaderHandler.java:185) ~[BKCommonLib-1.19.3-v2-1501.jar:?]
	at com.bergerkiller.bukkit.common.internal.CommonListener.onPluginEnable(CommonListener.java:76) ~[BKCommonLib-1.19.3-v2-1501.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-418]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.3.jar:git-Paper-418]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.3.jar:git-Paper-418]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:203) ~[paper-1.19.3.jar:git-Paper-418]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.3.jar:git-Paper-418]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:561) ~[paper-1.19.3.jar:git-Paper-418]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:472) ~[paper-1.19.3.jar:git-Paper-418]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.19.3.jar:git-Paper-418]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-418]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-418]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by mfnalex** [comment]
Did you compile this yourself? Does it also happen using the version from SpigotMC? Did you do any changes to plugin.yml? Because that's definitely valid YAML and SnakeYAML should be able to parse it.

However, if you compiled this yourself, you can easily fix this by removing the following block from plugin.yml, it's basically useless anyway:

```yaml
awareness:
  - !@UTF8
```

**Comment by mfnalex** [comment]
Both, the version on github and on SpigotMC are working fine for me in latest paper 1.19.3 (build 420)

**Comment by PaladinFallen** [comment]
I didn't compile it myself, that is one thing I've yet to teach myself. Yes, this is the same version from SpigotMC. I haven't changed anything to the plugin.yml file, there was never a need too.

This was a issue for Multiverse Inventory as well, they just removed it. 
https://github.com/Multiverse/Multiverse-Inventories/issues/516#event-8597793602

Just wanted to make you aware.
